In [16]:
import pandas as pd  # Principal herramienta para manipulación tabular
import numpy as np   # Utilidades numéricas/condicionales (np.select, np.where)

In [17]:
# =====================================================
# 3. Lectura de Remittance
# =====================================================
# Leemos la tabla principal del Remittance: (ajustado a Excel)
remittance = pd.read_excel("Remittance_farmatodo.xlsx", skiprows=6, nrows=2000, header=[0, 1])
remittance.columns = [
    str(col[0]).strip() if "Unnamed" in str(col[1]) else str(col[1]).strip()
    for col in remittance.columns
]
# =====================================================
# 4. Limpieza de Remittance
# =====================================================    
remittance = remittance[["Nro Factura", "Descripción", "Total"]]
remittance = remittance.dropna(subset=["Nro Factura"]).reset_index(drop=True)
remittance = remittance.rename(columns={
    "Nro Factura": "Referencia / Factura",
    "Total": "Importe de Remittance"
})
remittance.head(20)

,Referencia / Factura,Descripción,Importe de Remittance
0,‭FV-XKZV33203‬,Acuerdo Fijo Mensual 01 2.3% - MASIVOS/MISCEL...,"-96.522.911,92"
1,‭FV-XKZV33397‬,Acuerdo Fijo Mensual 01 7% - MASIVOS/MISCELAN...,"-602.319,64"
2,‭FV-XKZV33514‬,EXHIBICIONES ADICIONALES NOVIEMBRE 2025,"-294.516.083,33"
3,‭NC-DC04-555537‬,Miscelaneos : Liquidaciones Ventas Pos-Folleto...,"-149.428.373,00"
4,‭CNQPMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,"-656.977,58"
5,‭PMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,"442.526.865,35"
6,‭NC-PMP1310723‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA (DPP),"-1.886.617,54"
7,‭NC-PMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA (DPP),"-7.437.426,31"
8,‭PMP1310723‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,"112.253.743,34"
9,‭NC-PMP1311231‬,OC:14013771 UNILEVER ANDINA COLOMBIA LTDA (DPP),"-26.792,64"
10,‭PMP1311231‬,OC:14013771 UNILEVER ANDINA COLOMBIA LTDA,"1.862.088,48"

In [18]:
remittance["Importe de Remittance"] = (
    remittance["Importe de Remittance"]
    .astype(str)
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .astype(float)
    .round(2)
)

remittance.head(20)

,Referencia / Factura,Descripción,Importe de Remittance
0,‭FV-XKZV33203‬,Acuerdo Fijo Mensual 01 2.3% - MASIVOS/MISCEL...,-9.652291e+07
1,‭FV-XKZV33397‬,Acuerdo Fijo Mensual 01 7% - MASIVOS/MISCELAN...,-6.023196e+05
2,‭FV-XKZV33514‬,EXHIBICIONES ADICIONALES NOVIEMBRE 2025,-2.945161e+08
3,‭NC-DC04-555537‬,Miscelaneos : Liquidaciones Ventas Pos-Folleto...,-1.494284e+08
4,‭CNQPMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,-6.569776e+05
5,‭PMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,4.425269e+08
6,‭NC-PMP1310723‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA (DPP),-1.886618e+06
7,‭NC-PMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA (DPP),-7.437426e+06
8,‭PMP1310723‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,1.122537e+08
9,‭NC-PMP1311231‬,OC:14013771 UNILEVER ANDINA COLOMBIA LTDA (DPP),-2.679264e+04
10,‭PMP1311231‬,OC:14013771 UNILEVER ANDINA COLOMBIA LTDA,1.862088e+06

In [10]:
remittance["Importe de Remittance"] = (
    remittance["Importe de Remittance"]
    .astype(str)
    .str.replace(r"\.(?=\d{3}(?:,|$))", "", regex=True)
    .str.replace(",", ".", regex=False)
    .pipe(pd.to_numeric, errors="coerce")
    .round(2)
)
remittance.head(20)

,Referencia / Factura,Descripción,Importe de Remittance
0,‭FV-XKZV33203‬,Acuerdo Fijo Mensual 01 2.3% - MASIVOS/MISCEL...,NaN
1,‭FV-XKZV33397‬,Acuerdo Fijo Mensual 01 7% - MASIVOS/MISCELAN...,-602319.64
2,‭FV-XKZV33514‬,EXHIBICIONES ADICIONALES NOVIEMBRE 2025,NaN
3,‭NC-DC04-555537‬,Miscelaneos : Liquidaciones Ventas Pos-Folleto...,NaN
4,‭CNQPMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,-656977.58
5,‭PMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,NaN
6,‭NC-PMP1310723‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA (DPP),NaN
7,‭NC-PMP1310724‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA (DPP),NaN
8,‭PMP1310723‬,OC:14013732 UNILEVER ANDINA COLOMBIA LTDA,NaN
9,‭NC-PMP1311231‬,OC:14013771 UNILEVER ANDINA COLOMBIA LTDA (DPP),-26792.64
10,‭PMP1311231‬,OC:14013771 UNILEVER ANDINA COLOMBIA LTDA,NaN